name    'bitlancer-motd'
version '0.0.1'
source 'https://github.com/Bitlancer/puppet-motd'
author 'Bitlancer LLC (contact@bitlancer.com)'
license 'Apache License, Version 2.0'
summary 'An MOTD Puppet Module'
description 'An MOTD Puppet Module'
project_page 'https://github.com/Bitlancer/puppet-motd'
